### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hasenradball** [franneck94/UdemyCppPro#1]
Hi,

wo kann ich denn Fragen stellen, die dann auch beantwortet werden?

**Comment by franneck94** [comment]
Auf Udemy oder Discord

**Comment by hasenradball** [comment]
Auf Udemy hatte ich es versucht.
Kam aber nie etwas zurück.
Daher dachte ich ich frage mal nach.

**Comment by franneck94** [comment]
Welche Frage war es denn?

**Comment by hasenradball** [comment]
Hatte Sie auch in Kapitel 2.15 Patterns formuliert.

a) Wenn ich die zum Beispiel die Optimierung auf -g -O3 einstelle, dann hat die erzeugte Datei statt 60 kB ca. 600 kB (in menem privaten Projekt).

b) wie gehtst Du damit um beim Compilieren mit mehreren Dateien wo nur einige einen bestimmten Include benötigen.
gibt Du dennoch den include beim Pattern an auch wenn nicht alle files den benötigen?
Die alternative wäre das Target wieder für jedes File einzel zu definieren.

**Comment by franneck94** [comment]
Hab dir bei Udemy geantwortet, sorry.

**Comment by franneck94** [comment]
wie gehtst Du damit um beim Compilieren mit mehreren Dateien wo nur einige einen bestimmten Include benötigen.

Beim Release Mode wird eh alles unnötige weg optimiert. Also wäre es nicht schlimm "zu viel" zu includen
